In [3]:
import pandas as pd
import requests

## John

In [17]:
url = ' https://api.openbrewerydb.org/breweries?&per_page=50'
resp = requests.get(url)
resp
data = resp.json()

In [18]:
## Create a dataframe using the api address above with every brewery in the database. 
# Will need to use page and per_page as parameters. per_page max is 50
brewDF = pd.DataFrame(data)
brewDF.shape

(50, 14)

In [19]:
brewDF.head()

,brewery_type,city,country,id,latitude,longitude,name,phone,postal_code,state,street,tag_list,updated_at,website_url
0,micro,Birmingham,United States,2,33.524521,-86.774322,Avondale Brewing Co,2057775456,35222-1932,Alabama,201 41st St S,[],2018-08-23T23:19:57.825Z,http://www.avondalebrewing.com
1,micro,Tuscaloosa,United States,4,33.1984907123707,-87.5621551272424,Band of Brothers Brewing Company,2052665137,35401-4653,Alabama,1605 23rd Ave,[],2018-08-23T23:19:59.462Z,http://www.bandofbrosbrewing.com
2,micro,Birmingham,United States,44,33.5128492349817,-86.7914000624146,Trim Tab Brewing,2057030536,35233-3401,Alabama,2721 5th Ave S,[],2018-08-23T23:20:31.423Z,http://www.trimtabbrewing.com
3,micro,Huntsville,United States,46,34.7277523,-86.5932014,Yellowhammer Brewery,2569755950,35805-3046,Alabama,2600 Clinton Ave W,[],2018-08-23T23:20:33.102Z,http://www.yellowhammerbrewery.com
4,micro,Wasilla,United States,55,61.5752695,-149.4127103,Bearpaw River Brewing Co,,99654-7679,Alaska,4605 E Palmer Wasilla Hwy,[],2018-08-23T23:20:40.743Z,http://bearpawriverbrewing.com

In [34]:
## Filter this data set down to only micro breweries in states that with begin and end with the same letter
estados = brewDF.state
brew_match = brewDF[[each[0].lower()==each[-1].lower() for each in estados]]

In [35]:

brew_match.head()

,brewery_type,city,country,id,latitude,longitude,name,phone,postal_code,state,street,tag_list,updated_at,website_url
0,micro,Birmingham,United States,2,33.524521,-86.774322,Avondale Brewing Co,2057775456,35222-1932,Alabama,201 41st St S,[],2018-08-23T23:19:57.825Z,http://www.avondalebrewing.com
1,micro,Tuscaloosa,United States,4,33.1984907123707,-87.5621551272424,Band of Brothers Brewing Company,2052665137,35401-4653,Alabama,1605 23rd Ave,[],2018-08-23T23:19:59.462Z,http://www.bandofbrosbrewing.com
2,micro,Birmingham,United States,44,33.5128492349817,-86.7914000624146,Trim Tab Brewing,2057030536,35233-3401,Alabama,2721 5th Ave S,[],2018-08-23T23:20:31.423Z,http://www.trimtabbrewing.com
3,micro,Huntsville,United States,46,34.7277523,-86.5932014,Yellowhammer Brewery,2569755950,35805-3046,Alabama,2600 Clinton Ave W,[],2018-08-23T23:20:33.102Z,http://www.yellowhammerbrewery.com
4,micro,Wasilla,United States,55,61.5752695,-149.4127103,Bearpaw River Brewing Co,,99654-7679,Alaska,4605 E Palmer Wasilla Hwy,[],2018-08-23T23:20:40.743Z,http://bearpawriverbrewing.com

In [43]:
brew_match[(brew_match.latitude == max(brew_match.latitude)) | (brew_match.latitude == min(brew_match.latitude)) |
          (brew_match.longitude == max(brew_match.longitude)) | (brew_match.longitude == min(brew_match.longitude))]

,brewery_type,city,country,id,latitude,longitude,name,phone,postal_code,state,street,tag_list,updated_at,website_url
1,micro,Tuscaloosa,United States,4,33.1984907123707,-87.5621551272424,Band of Brothers Brewing Company,2052665137,35401-4653,Alabama,1605 23rd Ave,[],2018-08-23T23:19:59.462Z,http://www.bandofbrosbrewing.com
4,micro,Wasilla,United States,55,61.5752695,-149.4127103,Bearpaw River Brewing Co,,99654-7679,Alaska,4605 E Palmer Wasilla Hwy,[],2018-08-23T23:20:40.743Z,http://bearpawriverbrewing.com
9,micro,Tucson,United States,107,32.201608314954,-110.821778571134,BlackRock Brewers,5202073203,85710-6767,Arizona,1664 S Research Loop Ste 200,[],2018-08-23T23:21:23.794Z,http://www.brb.beer

## Rie

In [93]:
import re

In [94]:
rieData = pd.read_csv("https://raw.githubusercontent.com/UCD-pbio-rclub/python-data-analysis_RieU/master/sRNAalignmentToTE.ForChap7Assignment.013119.csv")
rieData.head()

,totalReads,Aligned,notAligned,libName
0,1530841,37407 (2.44%),1493434 (97.56%),cot-EP-EP-1.qual.clipped.noRDNAorTDNA.Gmax_189...
1,526938,125711 (23.86%),401227 (76.14%),cot-EP-EP-1.qual.clipped.noRDNAorTDNA.Gmax_189...
2,2889626,816373 (28.25%),2073253 (71.75%),cot-EP-EP-1.qual.clipped.noRDNAorTDNA.Gmax_189...
3,1541795,40918 (2.65%),1500877 (97.35%),cot-EP-EP-2.qual.clipped.noRDNAorTDNA.Gmax_189...
4,629472,140798 (22.37%),488674 (77.63%),cot-EP-EP-2.qual.clipped.noRDNAorTDNA.Gmax_189...

In [107]:
#re.sub('[()]', '',rieData.Aligned[0]).strip().split(" ")

['37407', '2.44%']

In [119]:
rieData['Aligned'].apply(lambda x: re.sub('[()]', '',x).strip().split(" ") )

0        [37407, 2.44%]
1      [125711, 23.86%]
2      [816373, 28.25%]
3        [40918, 2.65%]
4      [140798, 22.37%]
5      [921828, 28.07%]
6        [44673, 8.87%]
7       [88989, 19.95%]
8      [198057, 19.40%]
9        [45898, 9.23%]
10      [94073, 23.79%]
11     [266291, 21.10%]
12       [45328, 5.29%]
13     [166246, 22.97%]
14     [633830, 24.65%]
15       [82179, 5.15%]
16     [309195, 26.34%]
17    [1214892, 24.18%]
18       [23627, 5.72%]
19      [55597, 13.51%]
20     [155607, 15.10%]
21       [42009, 5.87%]
22       [91045, 9.97%]
23     [294511, 15.64%]
24       [10340, 0.86%]
25       [33627, 8.85%]
26     [187886, 23.58%]
27        [8980, 0.81%]
28       [27952, 6.03%]
29     [153060, 23.42%]
            ...
42       [20931, 2.34%]
43      [46393, 13.44%]
44     [217918, 26.58%]
45       [16032, 1.56%]
46      [38972, 14.50%]
47     [191846, 25.49%]
48       [58847, 6.34%]
49     [182713, 20.24%]
50    [1073381, 25.73%]
51       [36362, 5.84%]
52     [115151, 15.60%]
53     [643854, 25.45%]
54       [31648, 2.76%]
55      [94223, 17.82%]
56    [1094310, 31.32%]
57       [17005, 2.26%]
58      [49114, 14.43%]
59     [590855, 34.02%]
60       [40105, 7.39%]
61      [79823, 18.10%]
62     [243406, 20.77%]
63       [49511, 9.15%]
64      [98203, 16.78%]
65     [244216, 20.51%]
66       [29159, 4.83%]
67      [93418, 20.98%]
68     [450682, 24.30%]
69       [31311, 4.10%]
70     [111421, 14.12%]
71     [559337, 24.58%]
Name: Aligned, Length: 72, dtype: object